In [4]:
import tensorflow as tf
print(tf.__version__)

1.9.0


In [5]:
hello = tf.constant('Hello World')
print(hello)

Tensor("Const_2:0", shape=(), dtype=string)


In [6]:
sess = tf.Session()
print(sess.run(hello))

b'Hello World'


In [7]:
# name 매개변수는 tensorboard를 위한 이름
x = tf.constant(35, name='x')
y = tf.Variable(x+5, name='y')

print(y)

<tf.Variable 'y:0' shape=() dtype=int32_ref>


In [8]:
model = tf.global_variables_initializer()
with tf.Session() as session:
    session.run(model)
    print(session.run(y))

40


In [9]:
a = tf.constant([1, 2, 3], name='a')
b = tf.constant(4, name='b')

add_op = a + b

with tf.Session() as session:
    print(session.run(add_op))

[5 6 7]


In [10]:
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)
add = tf.add(a,b)
mul = tf.multiply(a, b)
total = tf.multiply(add, mul)

with tf.Session() as sess:
    print(sess.run(add, feed_dict={a:2, b:3}))
    print(sess.run(mul, feed_dict={a:2, b:3}))
    print(sess.run(total, feed_dict={a:2, b:3}))

5
6
30


In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
product = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[12.]]


In [12]:
import numpy as np
a = np.zeros((3, 3))
ta = tf.convert_to_tensor(a)

with tf.Session() as sess:
    print(sess.run(ta))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
uniform = tf.random_uniform([3, 3, 3], minval=0.0, maxval=10)
normal = tf.random_normal([3, 3, 3], mean=0.0, stddev=2.0)
trunc = tf.truncated_normal([2, 2], mean=5.0, stddev=1.0)
random_var = tf.Variable(tf.truncated_normal([2, 2]))

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

print(sess.run(normal), end="\n\n")
print(sess.run(trunc), end="\n\n")
print(sess.run(random_var), end="\n\n")
print(sess.run(add), end="\n\n")
print(sess.run(num), end="\n\n")

[[[-1.8546010e+00 -6.1927271e-01  2.9231789e+00]
  [ 5.0756121e+00 -2.2579458e+00  8.5590146e-02]
  [-3.3502448e+00  1.1243314e+00  9.6353894e-01]]

 [[ 2.4544296e+00 -1.6372482e-01 -5.5730903e-01]
  [ 2.9169074e-01 -1.2434759e+00 -5.4932934e-01]
  [-2.5082357e+00  1.0426170e+00  5.7501066e-01]]

 [[ 2.4013665e+00 -1.1455604e+00  4.2244345e-03]
  [-5.0618035e-01  2.5404656e-01  2.6503766e-01]
  [ 1.5138626e+00  1.9333425e+00 -1.2748929e+00]]]

[[4.4979    3.8192906]
 [4.7450275 5.416217 ]]

[[ 0.20922293  0.8295708 ]
 [-0.5278091   0.842322  ]]



InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype int16
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_INT16, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_1', defined at:
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\asyncio\base_events.py", line 1425, in _run_once
    handle._run()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tornado\platform\asyncio.py", line 122, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\zmq\eventloop\zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\zmq\eventloop\zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\zmq\eventloop\zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\IPython\core\interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\IPython\core\interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\IPython\core\interactiveshell.py", line 2901, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-d045bafcd4ad>", line 2, in <module>
    b = tf.placeholder(tf.int16)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1734, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5927, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\framework\ops.py", line 3414, in create_op
    op_def=op_def)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\framework\ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder_1' with dtype int16
	 [[Node: Placeholder_1 = Placeholder[dtype=DT_INT16, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]


In [14]:
my_var = tf.Variable(0)
init = tf.global_variables_initializer()
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(init)
sess1.run(my_var.assign_add(5))
sess2.run(init)
sess2.run(my_var.assign_add(5))
print(sess1.run(my_var))
print(sess2.run(my_var))

5
5


In [15]:
sess = tf.Session()
diagonal = [[1,2,3,4], [5,6,7,8]]
print(tf.diag(diagonal))
sess.run(tf.diag(diagonal))

Tensor("Diag:0", shape=(2, 4, 2, 4), dtype=int32)


array([[[[1, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 2, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 3, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 4],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [5, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 6, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 7, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 8]]]])

In [16]:
input = [[1,0,0,0], [0,2,0,0], [0,0,3,0], [0,0,0,4]]
sess.run(tf.diag_part(input))

array([1, 2, 3, 4])

In [17]:
p = tf.placeholder(tf.float32, shape=[])
v2 = tf.constant(2.)
a = tf.add(p, v2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v2))
    print(sess.run(a, feed_dict={p:3.0}))
    try:
        sess.run(a)
    except Exception as e:
        print(e)

2.0
5.0
You must feed a value for placeholder tensor 'Placeholder_2' with dtype float
	 [[Node: Placeholder_2 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'Placeholder_2', defined at:
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\ipykernel\kernelapp.py", line 486, in start
    self.io_loop.start()
  File "C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tornado

In [18]:
my_tensor = tf.constant(0, shape=[6,2])
my_static_shape = my_tensor.get_shape()
print(type(my_static_shape))
print(my_static_shape)

print(my_static_shape.as_list())

my_tensor_transposed = tf.transpose(my_tensor)
print(my_tensor_transposed.get_shape())

my_placeholder = tf.placeholder(tf.float32, shape=[None,2])
print(my_placeholder.get_shape())

my_placeholder.set_shape([8,2])
print(my_placeholder.get_shape())

<class 'tensorflow.python.framework.tensor_shape.TensorShape'>
(6, 2)
[6, 2]
(2, 6)
(?, 2)
(8, 2)


In [19]:
tf.InteractiveSession()
a = tf.zeros(2)
print(a.eval())
print(tf.size(a))
print(tf.rank(a))

[0. 0.]
Tensor("Size:0", shape=(), dtype=int32)
Tensor("Rank:0", shape=(), dtype=int32)


In [20]:
def showvalue(t):
    sess = tf.InteractiveSession()
    tf.global_variables_initializer().run()
    print(t.eval())
    sess.close()

c2, c3 = tf.constant([1.2, 5.6]), tf.constant([-4, -1, 7])
v2, v3 = tf.Variable([2.3, 4.5]), tf.Variable([-2, 3, 5])
showvalue(tf.add_n([c2, v2]))
showvalue(tf.add_n([c3, v3, v3]))
showvalue(tf.abs(c2))
showvalue(tf.negative(c2))
showvalue(tf.sign([c2]))
showvalue(tf.sign([c2]))
showvalue(tf.square(c2))
showvalue(tf.round(c2))

[ 3.5 10.1]
[-8  5 17]
[1.2 5.6]
[-1.2 -5.6]
[[1. 1.]]
[[1. 1.]]
[ 1.44     31.359999]
[1. 6.]


C:\Users\acorn\Anaconda3\envs\zipline_test\lib\site-packages\tensorflow\python\client\session.py:1714: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [21]:
#  2x +  y  +  z =  1
#  4x + 3y + 4z =  2
# -4x + 2y + 2z = -6

#   2, 1, 1    x    1
#   4, 3, 4    y    2
#  -4, 2, 2    z   -6

# 역행렬 구하고 해를 찾음

In [22]:
sess = tf.Session()
x = tf.constant([2.0, 1.0, 1.0, 4, 3, 4, -4, 2, 2], shape=[3, 3])
print(sess.run(x))
y = tf.constant([1.0, 2, -6], shape=[3, 1])
print(sess.run(y))

[[ 2.  1.  1.]
 [ 4.  3.  4.]
 [-4.  2.  2.]]
[[ 1.]
 [ 2.]
 [-6.]]


In [23]:
z = tf.matrix_solve(x, y)
result = sess.run(z)
print("계수:", result)

계수: [[ 1.0000001]
 [-2.0000002]
 [ 1.0000001]]


In [24]:
print(2.0 * result[0] + 1.0 * result[1] + 1.0 * result[2])
print(sess.run(tf.matmul(x, z)))

[1.0000001]
[[ 1.0000001]
 [ 2.       ]
 [-6.000001 ]]


In [25]:
a = tf.constant([1,2,3,4,5,6], shape=[2,3])
a = tf.to_float(a)
s, u ,v = tf.svd(a)
s = tf.svd(a, compute_uv=False)
print(sess.run(s))
print(sess.run(u))
print(sess.run(v))

[9.508034   0.77286935]
[[-0.38631773 -0.92236584]
 [-0.92236584  0.38631773]]
[[-0.42866713  0.8059641 ]
 [-0.56630695  0.1123824 ]
 [-0.70394677 -0.58119917]]


In [26]:
sess = tf.Session()
a = tf.constant([1,2,3,4,5,6], shape=[2,3])
b = tf.constant([7,8,9,10,11,12], shape=[3,2])
c=tf.matmul(a,b)
sess.run(c)


a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2,2,3])
print(sess.run(a))
b = tf.constant(np.arange(13, 25, dtype = np.int32), shape=[2,3,2])
print(sess.run(b))
c = tf.matmul(a,b)
print(sess.run(c))



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
[[[ 94 100]
  [229 244]]

 [[508 532]
  [697 730]]]


In [27]:
a_1 = tf.range(1, 25, 1, dtype=tf.float32)
a = tf.reshape(a_1, (2, 2, 2, 3))
b_1 = tf.range(1, 25, 1, dtype=tf.float32)
b = tf.reshape(b_1, (2, 2, 3,2))
c = tf.matmul(a, b)
sess.run(c)

array([[[[  22.,   28.],
         [  49.,   64.]],

        [[ 220.,  244.],
         [ 301.,  334.]]],


       [[[ 634.,  676.],
         [ 769.,  820.]],

        [[1264., 1324.],
         [1453., 1522.]]]], dtype=float32)

In [53]:
# perm 순서를 작성한다. 0, 1, 2, 3의 순서
print(sess.run(a))
d = tf.matmul(a, tf.transpose(a, perm=[0, 1, 3, 2]))
sess.run(d)

[[[[ 1.  2.  3.]
   [ 4.  5.  6.]]

  [[ 7.  8.  9.]
   [10. 11. 12.]]]


 [[[13. 14. 15.]
   [16. 17. 18.]]

  [[19. 20. 21.]
   [22. 23. 24.]]]]


array([[[[  14.,   32.],
         [  32.,   77.]],

        [[ 194.,  266.],
         [ 266.,  365.]]],


       [[[ 590.,  716.],
         [ 716.,  869.]],

        [[1202., 1382.],
         [1382., 1589.]]]], dtype=float32)

In [29]:
# matmul 옵션을 이용해서 전치시킨다.
tf.matmul(a, a, transpose_b = True)

<tf.Tensor 'MatMul_7:0' shape=(2, 2, 2, 2) dtype=float32>

In [30]:
x = tf.constant([[1,2,3], [4,5,6]])
sess.run(tf.transpose(x))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
x = tf.constant([[[1, 2, 3],
                 [4, 5, 6],],
                [[7, 8, 9],
                [10, 11, 12]]])
print(sess.run(tf.shape(x)))
sess.run(tf.transpose(x))

[2 2 3]


array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [32]:
t = [[1, 2, 3], [4, 5, 6]]
paddings = [[1, 1,], [2, 2]]
print(sess.run(tf.pad(t, paddings, "CONSTANT")))

[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]


In [35]:
print(sess.run(tf.pad(t, paddings, "REFLECT")))

[[6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]
 [6 5 4 5 6 5 4]
 [3 2 1 2 3 2 1]]


In [36]:
print(sess.run(tf.pad(t, paddings, "SYMMETRIC")))

[[2 1 1 2 3 3 2]
 [2 1 1 2 3 3 2]
 [5 4 4 5 6 6 5]
 [5 4 4 5 6 6 5]]


In [39]:
#CNN에서 필터를 적용할 때 공간확보
t = [[1, 2, 3], [4, 5, 6]]
paddings = [[1, 1], [2, 2]] #행을 위 아래로 1개씩, 열을 앞 뒤로 2개씩 추가.
print(sess.run(tf.pad(t, paddings, "CONSTANT")))
paddings = [[1, 1], [1, 1]]
print(sess.run(tf.pad(t, paddings, "REFLECT"))) #반사!
print(sess.run(tf.pad(t, paddings, "SYMMETRIC"))) #대칭값!

import tensorflow as tf
x = tf.constant(35, name='x')
print(x)
y = tf.Variable(x+5, name='y')

with tf.Session() as session:
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("/tmp/basic", session.graph)
    model = tf.global_variables_initializer()
    session.run(model)
    print(session.run(y))

[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]
[[5 4 5 6 5]
 [2 1 2 3 2]
 [5 4 5 6 5]
 [2 1 2 3 2]]
[[1 1 2 3 3]
 [1 1 2 3 3]
 [4 4 5 6 6]
 [4 4 5 6 6]]
Tensor("x_2:0", shape=(), dtype=int32)
40


In [61]:
a_1 = tf.range(0, 8, 1, dtype=tf.float32)
a = tf.reshape(a_1, (2, 2, 2))
print(a.eval())
print()
print(tf.transpose(a).eval())

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]

[[[0. 4.]
  [2. 6.]]

 [[1. 5.]
  [3. 7.]]]

